### Wczytanie danych (i bibliotek)

# 1. Eksploracyjna analiza danych

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, roc_auc_score, confusion_matrix,
                              classification_report, roc_curve, mean_squared_error, 
                              r2_score, classification_report, confusion_matrix)
from sklearn.model_selection import RandomizedSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('Hotel Reservations.csv')
print(f"Liczba wierszy: {df.shape[0]}, liczba kolumn: {df.shape[1]}")
df.head()

Liczba wierszy: 36275, liczba kolumn: 19

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

### Typy danych i zmiennych

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36275 non-null  object
 1   no_of_adults                          36275 non-null  int64
 2   no_of_children                        36275 non-null  int64
 3   no_of_weekend_nights                  36275 non-null  int64
 4   no_of_week_nights                     36275 non-null  int64
 5   type_of_meal_plan                     36275 non-null  object
 6   required_car_parking_space            36275 non-null  int64
 7   room_type_reserved                    36275 non-null  object
 8   lead_time                             36275 non-null  int64
 9   arrival_year                          36275 non-null  int64
 10  arrival_month                         36275 non-null  int64
 11  arrival_date                          36275 non-null  int64
 12  market_segment_type                   36275 non-null  object
 13  repeated_guest                        36275 non-null  int64
 14  no_of_previous_cancellations          36275 non-null  int64
 15  no_of_previous_bookings_not_canceled  36275 non-null  int64
 16  avg_price_per_room                    36275 non-null  float64
 17  no_of_special_requests                36275 non-null  int64
 18  booking_status                        36275 non-null  object
dtypes: float64(1), int64(13), object(5)
memory usage: 5.3+ MB

In [4]:
print("Zmienne numeryczne")
df.describe()

Zmienne numeryczne

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests
count,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000
mean,1.844962,0.105279,0.810724,2.204300,0.030986,85.232557,2017.820427,7.423653,15.596995,0.025637,0.023349,0.153411,103.423539,0.619655
std,0.518715,0.402648,0.870644,1.410905,0.173281,85.930817,0.383836,3.069894,8.740447,0.158053,0.368331,1.754171,35.089424,0.786236
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2017.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,1.000000,0.000000,17.000000,2018.000000,5.000000,8.000000,0.000000,0.000000,0.000000,80.300000,0.000000
50%,2.000000,0.000000,1.000000,2.000000,0.000000,57.000000,2018.000000,8.000000,16.000000,0.000000,0.000000,0.000000,99.450000,0.000000
75%,2.000000,0.000000,2.000000,3.000000,0.000000,126.000000,2018.000000,10.000000,23.000000,0.000000,0.000000,0.000000,120.000000,1.000000
max,4.000000,10.000000,7.000000,17.000000,1.000000,443.000000,2018.000000,12.000000,31.000000,1.000000,13.000000,58.000000,540.000000,5.000000

In [5]:
print("Zmienne opisowe")
df.describe(include='object')

Zmienne opisowe

,Booking_ID,type_of_meal_plan,room_type_reserved,market_segment_type,booking_status
count,36275,36275,36275,36275,36275
unique,36275,4,7,5,2
top,INN00001,Meal Plan 1,Room_Type 1,Online,Not_Canceled
freq,1,27835,28130,23214,24390

# TODO 
### zrozumienie zmiennych? rozklady cech, korelacje, wykresy itd

### Sprawdzenie brakujących danych

In [6]:
print("Liczba brakujących wartości")
df.isnull().sum()

Liczba brakujących wartości

Booking_ID                              0
no_of_adults                            0
no_of_children                          0
no_of_weekend_nights                    0
no_of_week_nights                       0
type_of_meal_plan                       0
required_car_parking_space              0
room_type_reserved                      0
lead_time                               0
arrival_year                            0
arrival_month                           0
arrival_date                            0
market_segment_type                     0
repeated_guest                          0
no_of_previous_cancellations            0
no_of_previous_bookings_not_canceled    0
avg_price_per_room                      0
no_of_special_requests                  0
booking_status                          0
dtype: int64

In [7]:
print("Liczba duplikatów")
df.duplicated().sum()

Liczba duplikatów

np.int64(0)

In [8]:
# df['booking_status'].value_counts(normalize=True) # Można tym sprawdzić sobie stosunek cancelled/not cancelled

# 2. Przetwarzanie danych

### Usunięcie kolumny Booking_ID

In [9]:
df = df.drop('Booking_ID', axis = 1)
df.head()

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

### Kodowanie zmiennej docelowej

In [10]:
target = {'Canceled': 1, 'Not_Canceled': 0} # Zmiana booking_status na liczbe
df['booking_status'] = df['booking_status'].replace(target)
print("Canceled = 1, Not_Canceled = 0")
df.describe()

Canceled = 1, Not_Canceled = 0

,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,required_car_parking_space,lead_time,arrival_year,arrival_month,arrival_date,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
count,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000,36275.000000
mean,1.844962,0.105279,0.810724,2.204300,0.030986,85.232557,2017.820427,7.423653,15.596995,0.025637,0.023349,0.153411,103.423539,0.619655,0.327636
std,0.518715,0.402648,0.870644,1.410905,0.173281,85.930817,0.383836,3.069894,8.740447,0.158053,0.368331,1.754171,35.089424,0.786236,0.469358
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2017.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,1.000000,0.000000,17.000000,2018.000000,5.000000,8.000000,0.000000,0.000000,0.000000,80.300000,0.000000,0.000000
50%,2.000000,0.000000,1.000000,2.000000,0.000000,57.000000,2018.000000,8.000000,16.000000,0.000000,0.000000,0.000000,99.450000,0.000000,0.000000
75%,2.000000,0.000000,2.000000,3.000000,0.000000,126.000000,2018.000000,10.000000,23.000000,0.000000,0.000000,0.000000,120.000000,1.000000,1.000000
max,4.000000,10.000000,7.000000,17.000000,1.000000,443.000000,2018.000000,12.000000,31.000000,1.000000,13.000000,58.000000,540.000000,5.000000,1.000000

### Podział danych na zbiór treningowy, walidacyjny i testowy w proporcjach 60/20/20

In [11]:
X = df.drop('booking_status', axis = 1)
y = df['booking_status']

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.20, stratify=y)

In [12]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, stratify=y_train_val) # 0.25 * 0.80 = 0.20

### Kodowanie zmiennych kategorycznych

In [13]:
num_features = X_train.select_dtypes(include=["int64", "float64"]).columns.tolist()
cat_features = X_train.select_dtypes(include=["object", "category"]).columns.tolist()

print("Numeryczne cechy:", num_features)
print("Kategoryczne cechy:", cat_features)

Numeryczne cechy: ['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'required_car_parking_space', 'lead_time', 'arrival_year', 'arrival_month', 'arrival_date', 'repeated_guest', 'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled', 'avg_price_per_room', 'no_of_special_requests']
Kategoryczne cechy: ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']

In [14]:
num_pipeline = Pipeline(steps=[
    ('scaler', StandardScaler())
])
cat_pipeline = Pipeline(steps=[
    ('onehot', OneHotEncoder()) # handle_unknown='ignore', sparse_output=False
])
preprocessor = ColumnTransformer(transformers=[
    ("num", num_pipeline, num_features),
    ("cat", cat_pipeline, cat_features)
])

In [15]:
data_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor)
])

data_pipeline.fit(X_train)

feature_names = (
    pd.Index(data_pipeline.named_steps['preprocessor'].get_feature_names_out())
    .str.replace("num__", "", regex=False)
    .str.replace("cat__", "", regex=False)
)

X_train_processed = pd.DataFrame(data_pipeline.transform(X_train),
                                columns=feature_names)

X_val_processed = pd.DataFrame(data_pipeline.transform(X_val),
                                columns=feature_names)

X_test_processed = pd.DataFrame(data_pipeline.transform(X_test),
                                columns=feature_names)

# 3. Trening i ewaluacja modeli

In [16]:
def evaluate_model(model, X_tr, y_tr, X_v, y_v, name):
    model.fit(X_tr, y_tr)
    y_pred = model.predict(X_v)
    y_prob = model.predict_proba(X_v)[:, 1]
    return {
        'Model': name,
        'Accuracy':  np.round(accuracy_score(y_v, y_pred), 4),
        'Precision': np.round(precision_score(y_v, y_pred), 4),
        'Recall':    np.round(recall_score(y_v, y_pred), 4),
        'F1-Score':  np.round(f1_score(y_v, y_pred), 4),
        'ROC-AUC':   np.round(roc_auc_score(y_v, y_prob), 4),
    }

results = []
trained_models = {}

### Regresja logistyczna

In [17]:
lr = LogisticRegression(max_iter=1000, random_state=42)
res = evaluate_model(lr, X_train_processed, y_train, X_val_processed, y_val, 'Logistic Regression')
results.append(res)
trained_models['Logistic Regression'] = lr

for k, v in res.items():
    print(f"{k}: {v}")

Model: Logistic Regression
Accuracy: 0.8043
Precision: 0.7361
Recall: 0.6277
F1-Score: 0.6776
ROC-AUC: 0.8607

### Drzewo decyzyjne

In [18]:
dt = DecisionTreeClassifier()
res = evaluate_model(
    dt,
    X_train_processed, y_train,
    X_val_processed, y_val,
    'Decision Tree'
)

results.append(res)
trained_models['Decision Tree'] = dt

for k, v in res.items():
    print(f"{k}: {v}")

Model: Decision Tree
Accuracy: 0.8656
Precision: 0.7983
Recall: 0.7892
F1-Score: 0.7937
ROC-AUC: 0.8479

### Random forest

In [19]:
rf = RandomForestClassifier()

res = evaluate_model(
    rf,
    X_train_processed, y_train,
    X_val_processed, y_val,
    'Random Forest'
)

results.append(res)
trained_models['Random Forest'] = rf

for k, v in res.items():
    print(f"{k}: {v}")

Model: Random Forest
Accuracy: 0.8965
Precision: 0.8767
Recall: 0.796
F1-Score: 0.8344
ROC-AUC: 0.9472

In [ ]:
from scipy.stats import randint

param_dist = {
    'n_estimators': randint(100, 600),
    'max_depth': [None] + list(range(5, 50)),
    'min_samples_split': randint(2, 20),
    'min_samples_leaf': randint(1, 10),
}

random_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(),
    param_distributions=param_dist,
    n_iter=60,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

print("Szukanie najlepszych parametrów..")
random_search.fit(X_train_processed, y_train)

print("Najlepsze znalezione parametry:", random_search.best_params_)

best_rf = random_search.best_estimator_
res_tuned = evaluate_model(best_rf, X_train_processed, y_train, X_val_processed, y_val, 'Tuned Random Forest')

trained_models['Tuned Random Forest'] = best_rf

print("\nWyniki modelu po tuningu na zbiorze walidacyjnym:")
for k, v in res_tuned.items():
    print(f"{k}: {v}")

Rozpoczynam szukanie najlepszych parametrów. To może chwilę potrwać...
Najlepsze znalezione parametry: {'n_estimators': 300, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': 40}

Wyniki modelu po tuningu na zbiorze walidacyjnym:
Model: Tuned Random Forest
Accuracy: 0.897
Precision: 0.8784
Recall: 0.796
F1-Score: 0.8351
ROC-AUC: 0.9495

# TODO zmienić randomsearch na gridsearch może

## Porównanie modeli

In [21]:
results_df = pd.DataFrame(results).set_index('Model')
print("Porównanie modeli na zbiorze walidacyjnym")
print(results_df)

print("\nNajlepszy model wg. metryki")
for col in results_df.columns:
    best = results_df[col].idxmax()
    print(f"  {col:12s}: {best} ({results_df.loc[best, col]:.4f})")

Porównanie modeli na zbiorze walidacyjnym
                     Accuracy  Precision  Recall  F1-Score  ROC-AUC
Model
Logistic Regression    0.8043     0.7361  0.6277    0.6776   0.8607
Decision Tree          0.8656     0.7983  0.7892    0.7937   0.8479
Random Forest          0.8965     0.8767  0.7960    0.8344   0.9472

Najlepszy model wg. metryki
  Accuracy    : Random Forest (0.8965)
  Precision   : Random Forest (0.8767)
  Recall      : Random Forest (0.7960)
  F1-Score    : Random Forest (0.8344)
  ROC-AUC     : Random Forest (0.9472)

## Wybór najlepszego modelu i ewaluacja na zbiorze testowym